Traceback (most recent call last):
  File "/scratch/eb162/GAM_Repo/JP/fit_dataset_auto.py", line 55, in <module>
    gam_raw_inputs, counts, trial_idx, info_dict, var_names = parse_fun(table['path_file'][job_id])
  File "/scratch/eb162/GAM_Repo/JP/fit_dataset_auto.py", line 47, in <lambda>
    parse_fun = lambda path_remote: parse_mat_remote(path_remote, local_path, job_id, neuron_id)
  File "/scratch/eb162/GAM_Repo/JP/parsing_tools.py", line 81, in parse_mat_remote
    file_name = os.path.basename(scp_file)
  File "/scratch/eb162/GAM_Repo/JP/parsing_tools.py", line 81, in parse_mat_remote
    file_name = os.path.basename(scp_file)
  File "/share/apps/anaconda3/2020.02/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/share/apps/anaconda3/2020.02/lib/python3.7/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
te-packages/scipy/io/matlab/mio.py", line 224, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/share/apps/anaconda3/2020.02/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/scratch/eb162/venv/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/scratch/eb162/venv/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '106_gam_preproc_neu407_ACAd_CSP011_2020-07-29_002.mat'
